name: focus_life
description: A focus app with life progression
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # App monitoring
  app_usage: ^4.0.1

  # Background service
  flutter_background_service: ^5.1.0
  workmanager: ^0.7.0

  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  provider: ^6.1.5

  app_settings: ^5.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true